### ISSUE TITLE
[BUG] Import OPML

### ISSUE THREAD

**Issue by And96** [tughi/aggregator-android#11] opened 2020-05-02 18:52 UTC
Version: Preview 028.
Using "LOAD OPML FILE" button in find feeds page:
- Categories/Tags are not imported.
- App force close after import. (However everything seems imported correctly)

**Comment by tughi** [comment] 2020-05-02 19:17
I cannot reproduce the crash using my own [OPML file](https://raw.githubusercontent.com/tughi/aggregator-python/master/subscriptions.xml).

Did you submit a bug report from your device?

**Comment by And96** [comment] 2020-05-02 21:20
How?

**Comment by tughi** [comment] 2020-05-03 05:30
If an app force closes, Android used to show a dialog where you have the option to submit a bug report...

What's the Android version?

**Comment by And96** [comment] 2020-05-03 09:23
Bug report dialog appears only if an app crash multiple time. (At least on my device) However AdBlockers may block it (I think).

I am on Android 10

I uploaded the OPML file here: 

https://send.firefox.com/download/91c6531f7211fbfc/#lmStvNiEHZJqZGo62zsNpA

**Comment by tughi** [comment] 2020-05-03 09:30
Got it! You have a lot of feeds :-)

    java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
        at android.os.Parcel.createException(Parcel.java:1958)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:184)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
        at com.tughi.aggregator.services.FaviconUpdateScheduler.schedule(FaviconUpdateScheduler.kt:30)
        at com.tughi.aggregator.OpmlImportActivity$onCreate$2$1$1$1$1.invokeSuspend(OpmlImportActivity.kt:127)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:871)
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2554)
        at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:60)
        at android.os.Binder.execTransact(Binder.java:731)

**Comment by And96** [comment] 2020-05-03 10:43
Wow!

**Comment by tughi** [comment] 2020-05-04 19:13
Fixed in Preview-029

**Closed by tughi** 2020-05-04 19:13 UTC
Labels: bug
