### ISSUE TITLE
Refresh RSS Feeds Feature

### ISSUE THREAD

**Issue by HonestAbe7** [tughi/aggregator-android#70] opened 2022-12-03 17:41 UTC
I don't see a way to refresh the RSS feed list manually to check for any new updates if I start the app. I was expecting maybe to pull down the list and it would refresh the list. I do like the option to set the interval to check for updates.

**Comment by tughi** [comment] 2023-02-04 07:21
Duplicate of #74

**Closed by tughi** 2023-02-04 07:21 UTC
Labels: question
